spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wasla_test
    username: wasla
    password: secret

  data:
    redis:
      host: localhost
      port: 6379

  flyway:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    com.example.wasla: DEBUG
